export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_COUNTRY = 'SET_COUNTRY'

// base
export const FETCH_ARTICLES = 'FETCH_ARTICLES'
export const FETCH_MORE_ARTICLES = 'FETCH_MORE_ARTICLES'

// request
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST'
export const FETCH_MORE_ARTICLES_REQUEST = 'FETCH_MORE_ARTICLES_REQUEST'

// success
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_MORE_ARTICLES_SUCCESS = 'FETCH_MORE_ARTICLES_SUCCESS'

// failure
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE'
export const FETCH_MORE_ARTICLES_FAILURE = 'FETCH_MORE_ARTICLES_FAILURE'
